# Spring Configuration
spring:
  application:
    name: "desmos-blockchain-connector"
  main:
    web-application-type: reactive
  r2dbc:
    url:
    username:
    password:
    generate-unique-name: true
  flyway:
    url:
    locations: classpath:db/migration

# Spring Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.desmos: INFO

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Server Configuration
server:
  port: 8080

# Application Configuration
openapi:
  server:
    url: "https://localhost:9091"
    description: "Blockchain Connector Test Server"
  info:
    title: "Blockchain Connector"
    version: "2.0.0-SNAPSHOT"
    description: "Blockchain Connector Component"
    termsOfService: "https://example.com/terms-of-service"
    license:
      name: "Apache 2.0"
      url: "https://www.apache.org/licenses/LICENSE-2.0.html"
    contact:
      email: "info@example.com"
      name: "john doe"
      url: "https://example.com"

# Operator Configuration
operator:
  organizationIdentifier:

# Desmos Configuration
api:
  externalDomain: "http://localhost:8080"

# Context Broker Configuration
broker:
  provider:
  externalDomain:
  internalDomain:
  paths:
    entities: "/ngsi-ld/v1/entities"
    entityOperations: "/ngsi-ld/v1/entityOperations"
    subscriptions: "/ngsi-ld/v1/subscriptions"
    temporal: "/ngsi-ld/v1/temporal/entities"

# NGSI Subscription Configuration
ngsi-subscription:
  notificationEndpoint:

# DLT Adapter Configuration
dlt-adapter:
  provider:
  internalDomain:
  externalDomain:
  paths:
    publication: "/api/v1/publishEvent"
    subscription: "/api/v1/subscribe"
    events: "/api/v1/events"

# Event Subscription Configuration
tx-subscription:
  notificationEndpoint:

security:
  privateKey: "0x1aff50dca1ac463a5af99a858c2eef7517b8e46d3bf84723ff6dcfead7dc8db6"
  learCredentialMachineInBase64:

# Access Node
access-node:
  trustedAccessNodesList: "https://raw.githubusercontent.com/DOME-Marketplace/trust-framework/refs/heads/main/sbx/trusted_access_nodes_list.yaml"

external-access-nodes:
  urls: "https://desmos.dome-marketplace-sbx.org"

#TODO change to SBX
verifier:
  externalDomain: "https://verifier.dome-marketplace-lcl.org"

pep:
  externalDomain: "http://pdp.evidenceledger.eu:8888/"
  path: "/authorize/v1/policies/authz"
