@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam BoxPadding 10

' -------------------- Headers -------------------- '

actor "Operator" as operator

box "Local Access Node" #LightBlue
    participant "DataSyncService" as data_sync_service
    boundary "Context Broker" as context_broker
end box

boundary "External Access Node" as external_access_node

' -------------------- Diagram -------------------- '

note over operator, external_access_node
    Discovery
end note

activate data_sync_service
data_sync_service -> context_broker++: GET /ngsi-ld/v1/entities/type=<type>&attrs=id
    note right of context_broker
      [
        { "id": "urn:ngsi-ld:ProductOffering:<uuid>"},
        { "id": "urn:ngsi-ld:ProductOffering:<uuid>"},
        ...
      ]
    end note
return 200 OK Payload: local_entities_id_list

loop forEach configured Access Node
    data_sync_service -> external_access_node++: POST /sync/discovery
        note right of external_access_node
            This process is defined in the
            data_sync_discovery diagram.

            This process creates a sync job
            between the external and local
            as well as the local and external.
        end note
    return 202 Accepted Payload: external_entities_id_list
end

note over operator, external_access_node
    Sync
end note

@enduml
