@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam BoxPadding 10

' -------------------- Headers -------------------- '

actor "Operator" as operator

box "Local Access Node" #LightBlue
    participant "DataSyncService" as data_sync_service
    boundary "Context Broker" as context_broker
end box

boundary "External Access Node" as external_access_node

' -------------------- Diagram -------------------- '

activate data_sync_service

note over operator, external_access_node
    Sync
end note

data_sync_service -> data_sync_service: Compare local_entities_id_list\n with external_entities_id_list
data_sync_service -> external_access_node++: POST /sync/entities Payload: diff_entities_id_list
    note right of external_access_node
        This process is defined in
        the data_sync_retrieval
        diagram.
    end note
return 202 Accepted Payload: entities_list

loop for each entity in entities_list
    data_sync_service -> context_broker++: GET /ngsi-ld/v1/entities/<entity_id>
    context_broker --> data_sync_service: response
    alt "Entity exists"
        data_sync_service -> context_broker: PATCH /ngsi-ld/v1/entities/<entity_id>
        context_broker --> data_sync_service: 204 No Content
    else "Entity does not exist"
        data_sync_service -> context_broker: POST /ngsi-ld/v1/entities
        return 201 Created
    end
end

note over operator, external_access_node
    Completion
end note



@enduml
