@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam BoxPadding 10

' -------------------- Headers -------------------- '

actor "Operator" as operator

box "Local Access Node" #LightBlue
    control "DataSyncController" as data_sync_controller
    control "DataSyncScheduler" as data_sync_scheduler
    control "ApplicationRunner" as applicationRunner
    participant "P2PDataSyncWorkflow" as p2p_data_sync_workflow
    participant "BlockchainDataSyncWorkflow" as blk_data_sync_workflow
end box

' -------------------- Diagram -------------------- '

note over operator, blk_data_sync_workflow
    Trigger Data Synchronization
end note

alt "Bootstrapping"
    applicationRunner -> applicationRunner++: Application starts/restarts
    applicationRunner -> p2p_data_sync_workflow++: startP2PDataSyncProcess()
else "Scheduler"
    data_sync_scheduler -> data_sync_scheduler++: Cron job triggers
    data_sync_scheduler -> p2p_data_sync_workflow: startP2PDataSyncProcess()
else "DataSyncController"
    operator -> data_sync_controller++: GET /sync/data
    data_sync_controller -> blk_data_sync_workflow++: startBlockchainDataSyncProcess()
end

@enduml
