@startuml
'https://plantuml.com/sequence-diagram

title Discovery sync without events

autonumber

Origin -> ExternalAccessNode: POST /sync/discovery payload: origin_entities_id_list

ExternalAccessNode -> EAN_ContextBroker: GET /ngsi-ld/v1/entities/?type=ProductOffering

EAN_ContextBroker -> ExternalAccessNode: 200 payload: entities_id_list

ExternalAccessNode -> ExternalAccessNode: Compare entities

ExternalAccessNode -> Origin: POST /sync/entities payload: non_owned_entities_id_list

Origin -> ExternalAccessNode: 202 Accepted payload: entities_list

ExternalAccessNode -> EAN_ContextBroker: POST /ngsi-ld/v1/entityOperations/create payload: new_entities_list

EAN_ContextBroker -> ExternalAccessNode: 201 Created

ExternalAccessNode -> Origin: 200 payload: whole_entities_id_list

@enduml