@startuml
'https://plantuml.com/sequence-diagram

title Add new entities event

autonumber

boundary EventPublisher

EventPublisher -> ExternalAccessNode: Start params: issuer, origin_entities_id_list, broker_entities_list

ExternalAccessNode -> EAN_ContextBroker: GET /ngsi-ld/v1/entities/?type=ProductOffering

EAN_ContextBroker -> ExternalAccessNode: 200 payload: entities_ids_list

ExternalAccessNode -> ExternalAccessNode: Compare origin and broker entities

ExternalAccessNode -> Origin: POST /sync/entities payload: non_owned_entities_id_list

Origin -> ExternalAccessNode: 202 Accepted payload: entities_list

ExternalAccessNode -> EAN_ContextBroker: POST /ngsi-ld/v1/entityOperations/create payload: entities_list

EAN_ContextBroker -> ExternalAccessNode: 201 Created

@enduml