@startuml
'https://plantuml.com/sequence-diagram

'---------- Config ----------------

autonumber

'---------- Header ----------------

boundary "External Access Node" as ean

box "Access Node"

  control "P2PDataSyncController" as p2pController
  participant "P2PDataSyncWorkflow" as p2pWorkflow
  participant "BrokerPublisherService" as begs
  participant "BrokerAdapterService" as bas
  participant "Context Broker" as cb

end box

'---------- Diagram ----------------

ean -> p2pController++: POST /sync/p2p/entities \nPayload: EntitySyncRequest

note right of ean
    EntitySyncRequest:
        List<Id> entityIds
    Id:
        String id
end note

    p2pController -> p2pWorkflow++: getLocalEntities()
        p2pWorkflow -> begs++: getAllByType(String type)
            begs -> bas++: getAllByType(String type)
                bas -> cb++: GET /ngsi-ld/v1/entities?type={type}
                return 200 OK - Payload: BrokerGetEntitiesResponse

                note left of cb
                    ScorpioGetEntitiesResponse:
                        BrokerEntities[] brokerEntities
                end note

            return BrokerEntities[]
        return List<BrokerEntities>
            p2pWorkflow -> p2pWorkflow++: getEntitiesRelationshipsIds(List<BrokerEntities>)
            return List<Ids> entitiesRelationshipsIds
        p2pWorkflow -> begs++: getEntitiesRelationshipsByIds\n(List<Ids> entitiesRelationshipsIds)
            loop for each entity in entitiesRelationshipsIds
                begs -> bas++: getEntityById(String)
                    bas -> cb++: GET /ngsi-ld/v1/entities/{entityRelationshipId}
                    return 200 OK - Payload: String entityRelationship
                return String entityRelationship
            end
            return List<String> entityRelationship
            p2pWorkflow -> p2pWorkflow++: getEntitiesList(\nList<ScorpioProductOffering>,\n List<String> entitiesRelationships)
            return List<String> localEntities
        return List<String> localEntities
return 200 OK - Payload: DiscoverySyncResponse

note left of p2pController
    EntitySyncResponse:
        JsonNode entities
end note
@enduml